### ISSUE TITLE
Werte Aktuallisieren und nicht ändern

### ISSUE THREAD

**Issue by tobst96** [TA2k/ioBroker.parcel#10]
Moin,

ich würde gerne diese Werte auf Änderung Prüfen, um ein PopUp in der VIS zu realisieren. Leider werden die alle 10min beschrieben, allerdings ohne Änderung. Somit müssten die aus dem Adapter nur Aktualisiert werden und nicht beschrieben.

![image](https://user-images.githubusercontent.com/52480593/155474619-35506931-7970-4002-ae7c-0a9b7e2f97ab.png)

**Comment by TA2k** [comment]
Ist es nicht einfacher das lastchanged lc attribut zu überprüfen?

**Comment by mkshb** [comment]
Moin,

möchte mich hier gern anschließen.
Ich würde die Parameter gern für Benachrichtigungen benutzen. Wenn sich parcel.0.inDeliveryCount ändert und > 0 ist, dann mittels JavaScript ein Script triggern welches mir eine Mitteilung schickt.
Der Inhalt von parcel.0.inDeliveryCount wird jedoch bei jedem Durchlauf erst auf 0 gesetzt und dann wieder mit dem aktuellen Wert aktualisiert. Dadurch wird bei jedem Durchlauf das Sktipt getriggert. 

Danke und Grüße

**Comment by TA2k** [comment]
@mkshb Das war nicht ganz korrekt bitte mit der aktuelle Github version erneut testen

**Comment by mkshb** [comment]
Getestet und für gut befunden. Danke für die schnelle Umsetzung.
