### ISSUE TITLE
parcel.0.inDelivery mit falschem Typ

### ISSUE THREAD

**Issue by Grothesk242** [TA2k/ioBroker.parcel#11]
Ich selber habe zwar keine Ahnung, aber lt. diesem Thread: 
https://forum.iobroker.net/topic/52861/ideen-zur-t%C3%BCr%C3%B6ffnung/7?_=1645731560002
hat der DP einen falschen Typ. 
Statt 
"type": "json",
sollte es wohl 
"type": "string",
lauten. Siehe auch https://www.iobroker.net/#de/documentation/basics/roles.md

**Comment by TA2k** [comment]
fixed
