### ISSUE TITLE
V0.0.8 startet nicht

### ISSUE THREAD

**Issue by guergen1** [TA2k/ioBroker.parcel#12]
js-controller: 4.0.15
node.js: 14.19.0
npm: 6.14.16
parcel: 0.0.8

Der Adapter startet erst gar nicht:

`
host.iob | 2022-02-25 16:53:57.858 | error | instance system.adapter.parcel.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iob | 2022-02-25 16:53:57.858 | error | Caught by controller[0]: }
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:   code: 'ERR_DLOPEN_FAILED'
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:101:18)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
host.iob | 2022-02-25 16:53:57.857 | error | Caught by controller[0]:                  ^
host.iob | 2022-02-25 16:53:57.856 | error | Caught by controller[0]:   return process.dlopen(module, path.toNamespacedPath(filename));
host.iob | 2022-02-25 16:53:57.856 | error | Caught by controller[0]: internal/modules/cjs/loader.js:1144
`

**Comment by TA2k** [comment]
`
cd /opt/iobroker
npm install canvas
`

**Comment by guergen1** [comment]
Läuft...!
