### ISSUE TITLE
GLS Status INDELIVERY

### ISSUE THREAD

**Issue by mkshb** [TA2k/ioBroker.parcel#17]
Moin,

GLS Sendungen mit dem Status INDELIVERY landen nicht Objekt parcel.0.inDelivery.
Anbei das JSON dreier Sendungen von denen eine heute in Zustellung ist.

Danke für die Arbeit!

Grüß
[jsonGLS.txt](https://github.com/TA2k/ioBroker.parcel/files/8407392/jsonGLS.txt)
e

**Comment by TA2k** [comment]
Mir haben noch die states gefgehlt ist jetzt in der github version drin

**Comment by mkshb** [comment]
Wow, das ging fix. Danke für die Anpassungen!

Allerdings funktioniert es bei mir nicht. Habe über GitHub aktualisiert, jedoch taucht die Sendung nicht in inDelivery auf.

Kann ich helfen und Dir irgendwelche Infos zukommen lassen?

**Comment by TA2k** [comment]
Bitte nochmal

**Comment by mkshb** [comment]
Danke nochmal für die schnelle Anpassung. 
Dass ich das bei GLS mal sagen würde hätte ich nicht gedacht, aber "leider" wurde das Paket zwischenzeitlich zugestellt. Kann also nicht abschließend testen.
