### ISSUE TITLE
Amazon Fehlermeldung

### ISSUE THREAD

**Issue by Michel83** [TA2k/ioBroker.parcel#19]
Die Datenabfrage Funktioniert, allerdings bekomme ich im Log von Iobroker diese Fehlermeldung:

`"<html>\n <head>\n <meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\"/>\n <title>Seite wurde nicht gefunden</title>\n\n <style type=\"text/css\">\n a:link { font-family: verdana,arial,helvetica,sans-serif; color: #004B91; }\n a:visited { font-family: verdana,arial,helvetica,sans-serif; color: #996633; }\n a:active { font-family: verdana,arial,helvetica,sans-serif; color: #FF9933; }\n </style>\n </head>\n <body bgcolor=\"#FFFFFF\" text=\"#000000\" style=\"font-family: verdana,arial,helvetica,sans-serif;\">\n <!--\n Um über den automatisierten Zugriff auf Amazon-Daten zu sprechen, wenden Sie sich bitte an api-services-support@amazon.com.\r\n\r\nWeitere Informationen über die Migration zu unseren APIs finden Sie in unseren Marketplace APIs unter https://developer.amazonservices.com/ref=rm_5_sv bzw. in unserer Product Advertising API, wenn es sich um Anwendungsfälle im Rahmen von Werbung handelt: https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html/ref=rm_5_ac.\n -->\n <center>\n <a href=\"/ref=cs_404_logo\">\n <img src=\"https://images-eu.ssl-images-amazon.com/images/G/03/ShoppingPortal/logo._TTD_.png\"\n alt=\"Amazon\" border=\"0\"/>\n </a>\n <table border=\"0\" align=\"center\" style=\"margin-top: 20px;\">\n <tr>\n <td>\n <img src=\"https://images-eu.ssl-images-amazon.com/images/G/03/x-locale/common/kailey-kitty._TTD_.gif\" width=\"40\" height=\"35\" border=\"0\">\n </td>\n <td>\n <b style=\"color:#E47911\">Suchen Sie etwas?</b>\n <br/>\n Tut uns leid.  Die eingegebene Webadresse ist keine funktionsfähige Seite auf unserer Website.\n <br/><br/>\n <img src=\"https://images-eu.ssl-images-amazon.com/images/G/03/x-locale/common/orange-arrow._TTD_.gif\" width=\"10\" height=\"9\" border=\"0\">\n <b><a href=\"/ref=cs_404_link\">Klicken Sie hier, um zur Amazon-Startseite zurückzukehren.</a></b>\n </td>\n </tr>\n </table>\n </center>\n </body>\n</html>\n<!-- 764fd722 --><!-- sp:error_pages -->"`

`Error: Request failed with status code 404`

**Comment by chris76e** [comment]
Bei mir die selbe Meldung

**Comment by n3roGit** [comment]
Bei mir auch.
Außerdem werden zwischendurch immer alte Amazon Bestellungen erneut als Benachrichtigung versendet.

**Comment by TA2k** [comment]
Kann ich nicht nachvollziehen bei mir bitte ein debug log aktivieren und mir die datei via mail schicken
tombox2020@gmail.com

**Comment by Michel83** [comment]
Hi,

kurze Info der Fehler ist seit gestern weg. 

Grüße

**Comment by TA2k** [comment]
Fehler lag also bei Amazon. Danke für das Feedback
