### ISSUE TITLE
Amazon - Längst gelieferte Sendung sind plötzlich 'in delivery'

### ISSUE THREAD

**Issue by Grothesk242** [TA2k/ioBroker.parcel#20]
Längst gelieferte Sendung sind plötzlich 'in delivery'.  
Auf der Amazon Webseite sind diese aber entsprechend bereits als 'Geliefert' markiert. 
Fehler beim parsen?

Adapter Version 0.0.15

**Comment by TA2k** [comment]
Bräuchte ich die information ausdem json datenpunkt
auch per mail tombox2020@gmail.com

**Comment by Grothesk242** [comment]
Hab die Sendungen jetzt ins Bestell-Archiv geschoben.
