### ISSUE TITLE
Pushover user not working

### ISSUE THREAD

**Issue by Net-Felix** [TA2k/ioBroker.parcel#27]
**Describe the bug**  
When messages are sent over pushover and a user/device is given, nothing happens

**To Reproduce**  
1. send messages to pushover.0
2. define a user (or device)

**Expected behavior**  
Message is only sent to specified device

**Versions:**  
 - Adapter version: v0v0v20
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Debian GNU/Linux 11 (bullseye)

**Additional context**  
when sending to pushover with users,

`sendInstance, { user: user, message: text, title: "Paketstatus" }`
should be
`sendInstance, { device: user, message: text, title: "Paketstatus" }`

like described here: [Pushover Usage](https://github.com/ioBroker/ioBroker.pushover/blob/master/docs/de/README.md#usage)

**Comment by TA2k** [comment]
Fixed this in GitHub please test again

**Comment by Net-Felix** [comment]
nice, notifications are working now
