### ISSUE TITLE
Amazon Login mit 3 Accounts nicht möglich

### ISSUE THREAD

**Issue by Ullulaki** [TA2k/ioBroker.parcel#28]
Ich schaffe es leider nicht, mich mit der aktuellen Version, 0.0.2.1 bei Amazon einzuloggen.
Probiert habe ich es zunächst mit einem 2FA-Account, dort dann 2FA entfernt und da es noch nicht funktionierte anschließend einfach mit zwei non-2FA Accounts getestet - Fehler ist dabei immer folgender:
`Login to Amazon failed, please login to Amazon manually and check the login`

Erst einmal die Instanz gelöscht/neu hinzugefügt, dasselbe dann mit dem gesamten Adapter probiert: 
leider auch keine Veränderung.

Login bei DHL mit 2FA sowie den anderen Anbieteren, die ich verwende (Hermes, DPD, UPS) funktioniert alles problemlos.

Adapter auf Debug gestellt wirft mir folgenden zauberhaften Textabschnitt aus, mit dem ich leider nichts anzufangen weiß:
[Lognachricht 1.txt](https://github.com/TA2k/ioBroker.parcel/files/9591287/Lognachricht.1.txt)
[Lognachricht 2.txt](https://github.com/TA2k/ioBroker.parcel/files/9591288/Lognachricht.2.txt)

 - Adapter version: 0.0.21
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: "Debian GNU/Linux 11 im LXC-Container

**Comment by TA2k** [comment]
Funktioniert die 0.0.20?

**Comment by Ullulaki** [comment]
Ach merde, das wollte ich eigentlich vorher noch getestet haben!
Die 0.0.20 funktioniert direkt!
2FA: Speichere Nutzer/Passwort und bekomme direkt per SMS ein Einmalkennwort, das war bei 0.0.21 nicht der Fall.
Dann einfach frech wieder auf 0.0.21 geupdated und funktioniert immer noch.

**Comment by TA2k** [comment]
Wenn du Zeit hast könntest du parcel.0.auth löschen und dann via GitHub installieren ob es dann bei dir geht

**Comment by Ullulaki** [comment]
Also mit 0.0.20 lief es, dann Update per GitHub auf 0.0.21: lief! Nachdem parcel.0.auth gelöscht und Adapter neugestartet, Fehler wieder da:
`Login to Amazon failed, please login to Amazon manually and check the login`

**Comment by TA2k** [comment]
Und v0.0.22

**Comment by Ullulaki** [comment]
Sorry, nicht gesehen, dass ein Update kam.
Funktioniert mit 0.0.22 einwandfrei! :)
