### ISSUE TITLE
how to login to amazon ?

### ISSUE THREAD

**Issue by wubbl0rz** [TA2k/ioBroker.parcel#33]
sorry if its totally obvious but i don't understand how i can login to amazon. 

i enter mail + password and a token from the authenticator app (which are valid for around 30sec).
after save i receive a sms with a new token and the following error appears in the log. if i go to settings now and enter the token from the sms then i get the same error (and another sms with new token...). how do i "login manually" ?

version is 0.0.23 but i tried it a few weeks ago on an older version with the same result. 

![image](https://user-images.githubusercontent.com/30373916/195038524-a9f27461-7960-492e-ba0b-1b2aa4006fb0.png)

**Comment by wubbl0rz** [comment]
sekunde glaube ich weiß woran es liegen könnte... habe gerade im source folgendes gefunden

``` 
 if (res.data.indexOf("Meine Bestellungen") !== -1) {
```

könnte es sein das es probleme gibt weil meine amazon.de sprache standardmäßig auf englisch steht ? hmmm ich probiere das gleich mal aus :smile:

**Comment by wubbl0rz** [comment]
ja das ist es. wenn ich die default sprache auf deutsch stelle gehts. da wäre ich normal glaube nie drauf gekommen :laughing:  
evtl. ein kleiner hinweis in der readme ? könnte mir vorstellen gibt noch mehr die amazon.de verwenden aber als default sprache nicht auf deutsch.

**Comment by TA2k** [comment]
Danke für den Hinweis. Bitte mal die Github version probieren die müsste Sprachen unabhängig sein

**Comment by wubbl0rz** [comment]
damit geht das login gar nicht mehr. egal ob deutsch oder englisch :see_no_evil: ich muss aber auch gestehen das ich nicht der größte iobroker kenner bin aber denke schon das ich das richtig gemacht habe. die version wird ja auch als 0.0.23 (1~) angezeigt. hab den iobroker nur nebenbei für u.a. solche nicen plugins wie dieses hier :smile: 

![image](https://user-images.githubusercontent.com/30373916/195097887-68da9129-c070-4699-8657-8dfed560033f.png)

**Comment by TA2k** [comment]
Jetzt sollte es passen

**Comment by wubbl0rz** [comment]
nu gehts nice :rocket:
