### ISSUE TITLE
First DHL Login doesn't generate SMS/Mail anymore

### ISSUE THREAD

**Issue by jpmschuler** [TA2k/ioBroker.parcel#34]
**Describe the bug**  
Fresh ioBroker install with new parcel adapter won't allow DHL login

**To Reproduce**  
1. Go to parcel settings
2. add DHL user no and password
3. check logs, see messages 
parcel.0 | 2022-10-12 17:12:37.196 | info | Login to DHL
parcel.0 | 2022-10-12 17:12:37.905 | warn | Please enter email code in instance settings and press save
4. check phone and mail inbox but nothing

**Expected behavior**  
Get a code like ~12month ago I first tried this.

**Versions:**  
 - Adapter version: 0.0.23
 - JS-Controller version: 4.0.23
 - Node version: Node.js: v14.20.1
 - Operating system: docker iobroker/iobroker:latest

I tried to de- and reactivate 2-factor-auth for DHL at paket.de but it didn't make a difference.

**Comment by TA2k** [comment]
Gerade getestet mit MFA aktiv. sms erhalten und auch eingabe hat funktioniert. vielleicht mfa nochmal via sms probieren

**Comment by jpmschuler** [comment]
Danke! Okay gelöst, bin alles mehrfach durchgegangen und hab alles neu gemacht. Nochmal E-Mail-Adresse und Passwort eingetragen, dann erscheint 
```
parcel.0 | 2022-10-13 00:22:28.999 | warn | Please enter sms code in instance settings and press save
```
und ich bekomme SMS und es klappt.

Dann gesehen, dass vorher die Postnummer in Anmeldefeld stand und es gab eine andere Warning im Protokoll (Email code) und keine Bestätigung. Ist also eine Sackgasse, aber vermeidbar wenn man wirklich die Email-Adresse nutzt wie da steht. Sry für die Fehlbedienung, evtl. eine Prüfung auf integer mit Warnung an Deppen wie mich einrichten?

(Im DHL Kundenkonto kann man MFA für SMS nicht konfigurieren, nur MFA für E-Mail. MFA für SMS geht für diesen Login-Typ aber scheinbar automatisch)
