### ISSUE TITLE
Login nicht möglich bei " im Password

### ISSUE THREAD

**Issue by Rookiestyle** [TA2k/ioBroker.parcel#36]
Mein ursprüngliches Password für Hermes hatte ein ``"`` enthalten.
Der Login war nicht möglich, Fehler im Log
```
parcel.0 | 2022-12-23 21:58:30.343 | error | {"code":902,"message":"Die Daten wurden im falschen Format übertragen"}
parcel.0 | 2022-12-23 21:58:30.343 | error | AxiosError: Request failed with status code 400
```

Nachdem ich das Passwort geändert hatte, so dass es **kein** ``"`` mehr enthält, war der Login erfolgreich.

Das ist vermutlich nicht spezifisch für Hermes, sondern liegt am fehlenden *Escapen* dieses Zeichens beim Übergeben des Passworts hier:
```
data: `{"username":"${this.config.hermesusername}","password":"${this.config.hermespassword}"}`,
```
Ein ``\"`` würde funktionieren, ggf. muss auch ein ``\`` in ``\\`` umgesetzt werden

**Comment by TA2k** [comment]
fixed
