### ISSUE TITLE
warn: parcel.0 (234548) No Amazon orders found - LogLevel ändern?

### ISSUE THREAD

**Issue by Grothesk242** [TA2k/ioBroker.parcel#53]
In regelmäßigen Abstängen taucht im Log

```
2023-06-30 22:02:09.970  - warn: parcel.0 (234548) No Amazon orders found
2023-06-30 22:02:12.115  - info: parcel.0 (234548) Login to Amazon successful
```
auf. Kann man das auf ein anderes LogLevel hieven? Die Meldung ist nämlich korrekt, ich habe keine (offenen) Amazon Bestellungen. Muss ich aber nicht regelmäßig dran erinnert werden...

**Comment by TA2k** [comment]
die GitHub version gibt es als info aus
