### ISSUE TITLE
warning for hermes, no info in vis

### ISSUE THREAD

**Issue by j-r79** [TA2k/ioBroker.parcel#59]
I see every few minutes warnings in log:

parcel.0 | 2023-08-11 10:11:50.123 | info | undefined is not a valid state value for id "parcel.0.hermes.sendungen01.id"
-- | -- | -- | --
parcel.0 | 2023-08-11 10:11:50.020 | warn | This object will not be created in future versions. Please report this to the developer.
parcel.0 | 2023-08-11 10:11:50.018 | warn | Object parcel.0.hermes.sendungen01.id is invalid: obj.common.type has an invalid value (undefined) but has to be one of number, string, boolean, array, object, mixed, file, json

The Objects seem to be right, so my parcel is in delivery:

![image](https://github.com/TA2k/ioBroker.parcel/assets/5916790/683618ec-8e53-48d5-b3b1-4e7aed84d212)

But in VIS there is only the parcel, but no state, last line:

![image](https://github.com/TA2k/ioBroker.parcel/assets/5916790/c1fa155c-cddc-46bb-926b-59d3779aafbd)

**Expected behavior**  
VIS shows the right state and should not raise warnings...

**Comment by TA2k** [comment]
please try the github version and provide
parcel.0.hermes.sendungen01.status.parcelStatus

**Comment by j-r79** [comment]
Great, new version has no error and i see the state again in vis. Here is the information you requested:

parcel.0.hermes.sendungen01.status.parcelStatus: ZUGESTELLT
