### ISSUE TITLE
DHL Mail kommt  nicht

### ISSUE THREAD

**Issue by Lordcybertracker** [TA2k/ioBroker.parcel#6]
Hallo,
ich bin ja seit Jahren bei DHL angemeldet.
nun wollte ich das ausprobieren. 
Hab mein Login eingegeben aber darauf passiert nichts weiter.

Es kommt weder Mail noch SMS mit einem Code oder so.

Was mach ich falsch?

**Comment by TA2k** [comment]
Gibt es denn Fehler im log

**Comment by Lordcybertracker** [comment]
<html><body>


host.IOB |   | 2022-02-16 18:33:07.755 | info | Rebuild  for adapter system.adapter.parcel.0 not successful in 3 tries. Adapter  will not be restarted again. Please execute "npm install --production"  in adapter directory manually.
-- | -- | -- | -- | --
host.IOB |   | 2022-02-16 18:33:07.755 | error | Caught by controller[0]: }
host.IOB |   | 2022-02-16 18:33:07.755 | error | Caught by controller[0]:   code: 'ERR_DLOPEN_FAILED'
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:981:32)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:102:18)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
host.IOB |   | 2022-02-16 18:33:07.755 | error | instance system.adapter.parcel.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught  by controller[0]: Error: The module  '/opt/iobroker/node_modules/iobroker.parcel/node_modules/canvas/build/Release/canvas.node'
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught by controller[0]:   return process.dlopen(module, path.toNamespacedPath(filename));
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:981:32)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught  by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.parcel/node_modules/canvas/lib/bindings.js:3:18)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
host.IOB |   | 2022-02-16 18:33:07.754 | error | Caught by controller[0]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1185
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught by controller[0]:                  ^
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.IOB |   | 2022-02-16 18:33:07.753 | error | Caught by controller[0]: NODE_MODULE_VERSION 93. Please try re-compiling or re-installing


</body>
</html>

**Comment by TA2k** [comment]
`cd '/opt/iobroker/
npm install canvas`
