### ISSUE TITLE
undefined is not a valid state value for id "parcel.0.dpd.json"

### ISSUE THREAD

**Issue by patrickbs96** [TA2k/ioBroker.parcel#8]
**Describe the bug**  
Angemeldet mit DPD aber es sind aktuell keine Lieferungen vorhanden. 
Adapter ist frisch installiert, da das Updaten auf die aktuelle Version nicht funktioniert hatte.

**Versions:**  
 - Adapter version: <v0.0.4>

**Comment by TA2k** [comment]
Sollte behoben sein

**Comment by patrickbs96** [comment]
Danke für die schnelle Korrektur.

Leider lässt sich die neue Version nicht installieren:
![image](https://user-images.githubusercontent.com/49351462/154862586-b6558ff7-7792-4bfd-94e3-2a251dbf1c3e.png)

Eine Neuinstallation hat auch nicht geholfen

**Comment by TA2k** [comment]
Aber ich würde sagen das liegt nicht am Adapter

**Comment by patrickbs96** [comment]
Ein Neustart hat geholfen, danke dir 👍🏻
