### ISSUE TITLE
Sendestatus

### ISSUE THREAD

**Issue by Henny4184** [TA2k/ioBroker.parcel#9]
Kann mir jemand sagen warum ich keine Telegramm Nachricht bei Amazon Paketen bekomme. DHL Brief und Paket klappte Letzt Amazon aber gar nicht . Muss ich ein anderes Skript nutzen oder das andere abändern ? Oder funktioniert es einfach noch nicht ? Ansonsten ein Klasse Adapter .

**Comment by TA2k** [comment]
War ein Fehler im Adapter einfach neuinstallieren
